spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/prod_db
    username: postgres
    password: Querty1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true